# Generated by Django 3.2.25 on 2025-09-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/', verbose_name='تصویر پست'),
        ),
    ]
